SELECT OWNER,
TABLE_NAME,
COLUMN_NAME,
DATA_LENGTH
FROM dba_tab_columns
WHERE DATA_TYPE = 'VARCHAR2'
AND DATA_LENGTH > 1333
AND OWNER NOT IN ('SYS','SYSTEM','WKSYS','LBACSYS','XDB','CTXSYS','OUTLN','MDSYS','WMSYS', 'ORDSYS','OLAPSYS','SH','OE');